"""Main triage workflow orchestration.

This module implements the core support triage workflow that:
1. Fetches ticket from Linear (via linear-cli)
2. Analyzes validity using analysis-expert agent
3. Assesses severity using bug-hunter agent
4. Updates Linear with AI analysis and priority

The workflow is fail-safe: errors return TriageResult with success=False
rather than raising exceptions, allowing for graceful error handling.
"""

import logging
import time

from orchestrator.models import SeverityAnalysis, TriageResult, ValidityAnalysis
from orchestrator.utils import parse_llm_json, run_agent, run_cli_command

logger = logging.getLogger(__name__)


def execute_triage(ticket_id: str) -> TriageResult:
    """Execute support triage workflow.

    Steps (per docs/workflows.md lines 18-27):
    1. Fetch ticket from Linear
    2. Analyze validity (analysis-expert agent)
    3. Assess severity (bug-hunter agent)
    4. Update Linear with AI analysis

    Args:
        ticket_id: Linear ticket identifier (e.g., "ABC-123")

    Returns:
        TriageResult with all analysis data and execution metadata
    """
    start_time = time.time()

    try:
        # Step 1: Fetch ticket (docs/workflows.md lines 82-94)
        logger.info(f"Fetching ticket {ticket_id}")
        ticket_result = run_cli_command(
            ["linear-cli", "issue", "get", ticket_id, "--json"],
            timeout=30,
        )
        ticket_json = ticket_result.stdout

        # Step 2: Validity analysis (docs/workflows.md lines 96-120)
        logger.info("Analyzing validity")
        validity_raw = run_agent(
            agent_name="analysis-expert",
            task_description=f"Analyze validity: {ticket_json}",
        )
        validity_data = parse_llm_json(validity_raw)
        validity = ValidityAnalysis(**validity_data)

        # Step 3: Severity assessment (docs/workflows.md lines 122-148)
        logger.info("Assessing severity")
        severity_raw = run_agent(
            agent_name="bug-hunter",
            task_description=f"Assess severity: {ticket_json}",
        )
        severity_data = parse_llm_json(severity_raw)
        severity = SeverityAnalysis(**severity_data)

        # Step 4: Update Linear (docs/workflows.md lines 150-178)
        logger.info("Updating Linear")
        comment = format_ai_comment(validity, severity)
        run_cli_command(
            [
                "linear-cli",
                "issue",
                "update",
                ticket_id,
                "--priority",
                severity.severity,
                "--comment",
                comment,
            ],
            timeout=30,
        )

        duration = time.time() - start_time
        logger.info(f"Triage complete in {duration:.1f}s")

        return TriageResult(
            ticket_id=ticket_id,
            ticket_url=f"https://linear.app/issue/{ticket_id}",
            validity=validity,
            severity=severity,
            ai_comment=comment,
            success=True,
            duration=duration,
            agents_used=["analysis-expert", "bug-hunter"],
        )

    except Exception as e:
        duration = time.time() - start_time
        logger.error(f"Triage failed: {e}")
        # Return failure result instead of raising
        return TriageResult(
            ticket_id=ticket_id,
            ticket_url=f"https://linear.app/issue/{ticket_id}",
            validity=None,
            severity=None,
            ai_comment="",
            success=False,
            duration=duration,
            agents_used=[],
            error=str(e),
        )


def format_ai_comment(validity: ValidityAnalysis, severity: SeverityAnalysis) -> str:
    """Format AI analysis as Linear comment.

    Format per docs/workflows.md lines 162-178

    Args:
        validity: Validity analysis result
        severity: Severity assessment result

    Returns:
        Formatted markdown comment for Linear
    """
    missing_context_section = ""
    if validity.missing_context:
        items = "\n".join(f"- {item}" for item in validity.missing_context)
        missing_context_section = f"\n#### Missing Context\n{items}\n"

    return f"""## AI Triage Analysis

**Validity**: {"Valid" if validity.is_valid else "Invalid"}, {"Actionable" if validity.is_actionable else "Not Actionable"}
**Severity**: {severity.severity}
**Complexity**: {severity.complexity.capitalize()}
**Required Expertise**: {", ".join(severity.required_expertise) if severity.required_expertise else "None"}

### Validity Analysis
{validity.reasoning}
{missing_context_section}
### Severity Assessment
{severity.reasoning}

---
*Generated by Orchestrator*
"""
